export const ADD_PUBLICATIONS = 'ADD_PUBLICATIONS';
export const ORDERING_PUBLICATIONS = 'ORDERING_PUBLICATIONS';
export const SEARCHING_PUBLICATIONS = 'SEARCHING_PUBLICATIONS';
export const ADD_AUTHORS = 'ADD_AUTHORS';
export const SELECT_AUTHOR = 'SELECT_AUTHOR';
export const SELECT_PAGE = 'SELECT_PAGE';
