// PUblications seed data
module.exports = {
  up: (queryInterface) => queryInterface.bulkInsert('publications', [
    {
      author: 1,
      date: '2010-02-02',
      title: 'Trust',
      body: 'You can’t connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future.',
      time: '10:10:10',
    },
    {
      author: 1,
      date: '2020-02-02',
      title: 'Live your life',
      body: 'Your time is limited, so don’t waste it living someone else’s life.',
      time: '12:10:10',
    },
    {
      author: 1,
      date: '2013-02-02',
      title: 'Trust in your voice',
      body: 'Don’t let the noise of others’ opinions drown out your own inner voice.',
      time: '11:15:10',
    },
    {
      author: 1,
      date: '1992-02-02',
      title: 'Stay',
      body: 'Stay hungry. Stay foolish.',
      time: '08:10:10',
    },
    {
      author: 1,
      date: '1983-02-02',
      title: 'Today',
      body: 'If today were the last day of your life, would you want to do what you are about to do today?',
      time: '10:10:10',
    },
    {
      author: 1,
      date: '2010-02-02',
      title: 'Keep doing',
      body: 'I think the things you regret most in life are the things you didn’t do.',
      time: '05:10:10',
    },
    {
      author: 1,
      date: '2010-02-02',
      title: 'Trust',
      body: 'You can’t connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future.',
      time: '10:10:10',
    },
    {
      author: 1,
      date: '1998-02-02',
      title: 'Risk',
      body: 'Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.',
      time: '06:10:10',
    },
    {
      author: 1,
      date: '2010-02-02',
      title: 'Admit your mistakes',
      body: 'Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations.',
      time: '08:10:10',
    },
    {
      author: 2,
      date: '1945-02-02',
      title: 'Believe in yourself',
      body: 'I believe in intuitions and inspirations. I sometimes feel that I am right. I do not know that I am.',
      time: '08:10:10',
    },
    {
      author: 2,
      date: '1946-02-02',
      title: 'Focus',
      body: 'A man should look for what is, and not for what he thinks should be.',
      time: '08:10:10',
    },
    {
      author: 2,
      date: '1945-02-01',
      title: 'Humanity',
      body: 'I believe in standardizing automobiles. I do not believe in standardizing human beings.',
      time: '08:10:10',
    },
    {
      author: 2,
      date: '1945-02-02',
      title: 'Believe in yourself',
      body: 'I believe in intuitions and inspirations. I sometimes feel that I am right. I do not know that I am.',
      time: '08:10:10',
    },
    {
      author: 2,
      date: '1960-02-02',
      title: 'Be Happy',
      body: 'A table, a chair, a bowl of fruit and a violin; what else does a man need to be happy?',
      time: '08:10:10',
    },
  ]),
  down: (queryInterface) => queryInterface.bulkDelete('publications', {}, null),
};
